# Use C-Space as prefix
unbind C-b
set -g prefix C-Space

# Terminal settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-ghostty:RGB"
set -ag terminal-features ",xterm-ghostty:usstyle"

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf

# Disable bell
set -g bell-action none

# Increase scrollback buffer size
set -g history-limit 20000

# Define and plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'arl/gitmux' # install to path with `go install github.com/arl/gitmux@latest`
run '~/.config/tmux/plugins/tpm/tpm'

# Theme
set -g @catppuccin_flavor 'macchiato'

# Start windows and panes at index 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Full screen pane
bind f resize-pane -Z

# Create new window with current path
bind c new-window -c "#{pane_current_path}"

# Window naming
set -g set-titles off
set -g allow-rename off
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

# Swap windows with prefix + < / >
bind -r '<' swap-window -d -t -1
bind -r '>' swap-window -d -t +1

# Enable mouse mode
set -g mouse on

# Use vi key bindings to create and navigate between panes
bind H split-window -h -c "#{pane_current_path}" \;\
  swap-pane -U
bind L split-window -h -c "#{pane_current_path}"
bind J split-window -v -c "#{pane_current_path}"
bind K split-window -v -c "#{pane_current_path}" \;\
  swap-pane -U
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use vi key bindings for copy mode
bind v copy-mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi Escape send -X cancel

# Copy keybinds
set -g @prompt_regex '^➜ '

# Copy the previous command output
# I wish the below worked but it doesn't, wrapping it with run-shell does
# bind-key Y copy-mode \;\
#   send-keys -XF search-backward "#{@prompt_regex}" \;\
#   send-keys -XF search-backward "#{@prompt_regex}" \;\
#   send-keys -X cursor-down \;\
#   send-keys -X begin-selection \;\
#   send-keys -XF search-forward "#{@prompt_regex}" \;\
#   send-keys -X cursor-left \;\
#   send-keys -X copy-selection-and-cancel
bind-key y copy-mode \;\
  run-shell -b "tmux send-keys -XF search-backward \"#{@prompt_regex}\"; \
                tmux send-keys -XF search-backward \"#{@prompt_regex}\"; \
                tmux send-keys -X cursor-down; \
                tmux send-keys -X begin-selection; \
                tmux send-keys -XF search-forward \"#{@prompt_regex}\"; \
                tmux send-keys -X cursor-left; \
                tmux send-keys -X copy-selection-and-cancel"

# Status
set -g status-right-length 100
set -g status-right ''
set -ga status-right '#[bg=#{@thm_bg},fg=#{@thm_green}]#(gitmux "#{pane_current_path}")'
set -g window-status-format ' #I: #W '
set -g window-status-current-format ' #I: #W '
set -g window-status-style 'bg=#{@thm_bg},fg=#{@thm_blue}'
set -g window-status-current-style 'bg=#{@thm_blue},fg=#{@thm_bg},bold'
set -g window-status-last-style 'bg=#{@thm_bg},fg=#{@thm_green}'
set -g window-status-activity-style 'bg=#{@thm_bg},fg=#{@thm_red}'
set -gF window-status-separator '#[bg=#{@thm_bg},fg=#{@thm_fg}]|'

# Pass through keybindings
# example: bind -n C-l send-keys C-l

run 'echo "Reloaded tmux config, press ENTER to continue"'
